### ISSUE TITLE
Bech32 over Base58

### ISSUE THREAD

**Issue by ChristopherA** [openssi/peer-did-method-spec#1] opened 2019-03-11 18:32 UTC
I would recommend you consider a Bech32 encoding over Base58 as it is both error-correcting & error-detecting. It has some other superior properties. We are using it for did:btcr as well. https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

**Comment by mavarley** [comment] 2019-03-21 17:09
from https://en.bitcoin.it/wiki/Bech32:
_While this address format has been included in some implementations, as of December 2017, the address format is not recommended for use until more software supports the format._

Concerns for adoption? language and library support?

**Comment by ChristopherA** [comment] 2019-03-21 17:43
You are confusing a segwit address encoded using bech32, vs bech32 encoding of any number. In my opinion the bech32 encoding method for cryptographic numbers has strong benefits over base32, base58 or hex.

**Comment by dhh1128** [comment] 2019-03-27 16:45
I will go read up on it. Thanks for the suggestion, @ChristopherA .

**Comment by dhh1128** [comment] 2019-03-27 17:48
@lovesh, I know you have been wondering about the ideal format for payment addresses and want the format to include a checksum. Have you encountered Bech32 and pondered its suitability?

**Comment by lovesh** [comment] 2019-03-28 09:00
We already have a checksum in payment addresses as of now. I know a little about Bech32, its more readable (less prone to typos) due to lack of mixed case, is faster to generate the checksum and offers higher probabilty of fault detection. `bech32` sounds better but it has 2 disadvantages for Indy:
1. Takes more storage: Since Indy stores payment addresses (and DIDs, keys) as characters and not raw bytes, Bech32 address will take more space than base58.
2. Other entities like DIDs and keys are base58, payment addresses using bech32 will be an inconsistency.

**Comment by kdenhartog** [comment] 2019-05-09 07:27
Would Bech32 help us to not encounter that weird issue where an identifier can be 21 or 22 characters on Sov method spec? @lovesh

**Comment by dhh1128** [comment] 2019-05-14 19:53
@kdenhartog Yes, it would.

I am uncertain what to do about this issue. Bech32 seems to have some nice advantages, and Lovesh's comments about its inconsistency with Indy don't feel super important to me. This isn't an Indy DID method; it's general-purpose. However, shorter would be nicer. Can anybody tell me whether there's momentum behind Bech32 other than with the did:btcr method? Do we have any other evidence of mindshare (positive or negative)?

**Comment by ChristopherA** [comment] 2019-05-14 21:52
For me bech32 key advantage is both error-detection AND error-correction. I also like the lack of confusion in many fonts. Long-term no user should see a DID, but in peer usages they will sometimes read them aloud to each other.

**Comment by dhh1128** [comment] 2019-05-14 22:09
I agree with that summary, @ChristopherA .

I've recently been thinking about the did:git method that was designed at this last IIW. It's made me realize a nice characteristic of hex-based encodings as opposed to base-32/58/64 encodings: I can truncate the value without changing any of the retained characters. This is nice because, when reading DID values out of a log file or off a screen or over the phone, it allows the possibility of a short form, like git commit hashes do. Such a short form would be lossy and therefore inappropriate for machine processing, but it would sure be nice if users only had to read 8 hex characters to one another. Hex also has the virtue that case doesn't matter and that it doesn't use ambiguous characters, generally.

Of course, a simple hex encoding doesn't have the ED/ECC feature...

No strong opinion yet--just mulling it over.

**Comment by dhh1128** [comment] 2020-07-15 17:51
Closing this issue because we never got momentum around Bech32. I like it as an encoding. I think it's clever and has some nice properties. However, the spec and the impl decided to use some other formats to align more closely with did:key and to make DID docs look more like others we're seeing. I feel like we missed an opportunity here, and I regret it -- but I think the ship has sailed. :-(

**Closed as completed by dhh1128** 2020-07-15 17:51 UTC
